-- MySQL Script generated by MySQL Workbench
-- Чт 03 авг 2017 17:21:00
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `conferences`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `conferences` ;

CREATE TABLE IF NOT EXISTS `conferences` (
  `id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `countries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `countries` ;

CREATE TABLE IF NOT EXISTS `countries` (
  `id` INT NOT NULL,
  `name_en` VARCHAR(45) NULL,
  `name_ru` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `regions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `regions` ;

CREATE TABLE IF NOT EXISTS `regions` (
  `id` INT NOT NULL,
  `country_id` INT NULL,
  `name_en` VARCHAR(45) NULL,
  `name_ru` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_regions_country_idx` (`country_id` ASC),
  CONSTRAINT `fk_regions_country`
    FOREIGN KEY (`country_id`)
    REFERENCES `countries` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cities` ;

CREATE TABLE IF NOT EXISTS `cities` (
  `id` INT NOT NULL,
  `country_id` INT NULL,
  `region_id` INT NULL,
  `name_en` VARCHAR(45) NULL,
  `name_ru` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cities_country_idx` (`country_id` ASC),
  INDEX `fk_cities_region_idx` (`region_id` ASC),
  CONSTRAINT `fk_cities_country`
    FOREIGN KEY (`country_id`)
    REFERENCES `countries` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cities_region`
    FOREIGN KEY (`region_id`)
    REFERENCES `regions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `users` ;

CREATE TABLE IF NOT EXISTS `users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(191) NOT NULL,
  `password` VARCHAR(191) NOT NULL,
  `permissions` TEXT NULL,
  `last_login` TIMESTAMP NULL,
  `first_name_en` VARCHAR(191) NULL,
  `first_name_ru` VARCHAR(191) NULL,
  `middle_name_en` VARCHAR(50) NULL,
  `middle_name_ru` VARCHAR(50) NULL,
  `last_name_en` VARCHAR(191) NULL,
  `last_name_ru` VARCHAR(191) NULL,
  `country_id` INT NULL,
  `city_id` INT NULL,
  `degree_en` VARCHAR(45) NULL,
  `degree_ru` VARCHAR(45) NULL,
  `stitle_en` VARCHAR(45) NULL,
  `stitle_ru` VARCHAR(45) NULL,
  `affil_en` VARCHAR(255) NULL,
  `affil_ru` VARCHAR(255) NULL,
  `position_en` VARCHAR(150) NULL,
  `position_ru` VARCHAR(150) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `fk_users_city_idx` (`city_id` ASC),
  INDEX `fk_users_country_idx` (`country_id` ASC),
  CONSTRAINT `fk_users_country`
    FOREIGN KEY (`country_id`)
    REFERENCES `countries` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_city`
    FOREIGN KEY (`city_id`)
    REFERENCES `cities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
